# Setup Environment

In [1]:
!pip install pandas geopandas pyiceberg[s3fs,pyarrow] shapely

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (3.0.3)
Requirement already satisfied: geopandas in /opt/conda/lib/python3.11/site-packages (1.1.3)
Requirement already satisfied: shapely in /opt/conda/lib/python3.11/site-packages (2.1.2)
Requirement already satisfied: pyiceberg[pyarrow,s3fs] in /opt/conda/lib/python3.11/site-packages (0.11.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pyogrio>=0.7.2 in /opt/conda/lib/python3.11/site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from geopandas) (23.2)
Requirement already satisfied: pyproj>=3.5.0 in /opt/conda/lib/python3.11/site-packages (from geopandas) (3.7.2)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (5.2.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (2.31.0)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (8.4.1)
Requirement already satisfied: rich<15.0.0,>=10.11.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (14.3.4)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (1.7.3)
Requirement already satisfied: pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (2.13.4)
Requirement already satisfied: fsspec>=2023.1.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (2026.6.0)
Requirement already satisfied: pyparsing<4.0.0,>=3.1.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (3.3.2)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (1.1.0)
Requirement already satisfied: cachetools<7.0,>=5.5 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (6.2.6)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (0.21.0)
Requirement already satisfied: pyarrow>=17.0.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (24.0.0)
Requirement already satisfied: pyiceberg-core<0.9.0,>=0.5.1 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (0.8.0)
Requirement already satisfied: s3fs>=2023.1.0 in /opt/conda/lib/python3.11/site-packages (from pyiceberg[pyarrow,s3fs]) (2026.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.11/site-packages (from pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0->pyiceberg[pyarrow,s3fs]) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/conda/lib/python3.11/site-packages (from pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0->pyiceberg[pyarrow,s3fs]) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /opt/conda/lib/python3.11/site-packages (from pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0->pyiceberg[pyarrow,s3fs]) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.11/site-packages (from pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0->pyiceberg[pyarrow,s3fs]) (0.4.2)
Requirement already satisfied: certifi in /opt/conda/lib/python3.11/site-packages (from pyogrio>=0.7.2->geopandas) (2023.7.22)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->pyiceberg[pyarrow,s3fs]) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->pyiceberg[pyarrow,s3fs]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->pyiceberg[pyarrow,s3fs]) (2.0.7)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.11/site-packages (from rich<15.0.0,>=10.11.0->pyiceberg[pyarrow,s3fs]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.11/site-packages (from rich<15.0.0,>=10.11.0->pyiceberg[pyarrow,s3fs]) (2.16.1)
Requirement already satisfied: aiobotocore<4.0.0,>=2.19.0 in /opt/conda/lib/python3.11/site-packages (from s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (3.7.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 in /opt/conda/lib/python3.11/site-packages (from s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (3.14.1)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (0.13.0)
Requirement already satisfied: botocore<1.43.1,>=1.42.90 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (1.43.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (1.1.0)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (6.7.1)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (2.2.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (1.8.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2023.1.0->pyiceberg[pyarrow,s3fs]) (1.24.2)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=10.11.0->pyiceberg[pyarrow,s3fs]) (0.1.2)

In [2]:
import pandas as pd
import geopandas as gpd
import shapely.wkb
import os
from pyiceberg.catalog.rest import RestCatalog

ICEBERG_REST_URI = os.getenv("ICEBERG_REST_URI", "http://iceberg-rest:8181")
MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "http://minio:9000")
AWS_KEY = os.getenv("AWS_ACCESS_KEY_ID", "minioadmin")
AWS_SECRET = os.getenv("AWS_SECRET_ACCESS_KEY", "minioadmin")
ICEBERG_NS = "mch"


def _catalog():
    """
    Return a PyIceberg REST catalog connected to the local Iceberg REST server.

    PyIceberg catalog properties mirror the REST catalog spec:
      uri       – REST catalog endpoint
      s3.*      – S3FileIO properties for reading/writing the actual data files
    """

    return RestCatalog(
        name="local",
        **{
            "uri": ICEBERG_REST_URI,
            "s3.endpoint": MINIO_ENDPOINT,
            "s3.access-key-id": AWS_KEY,
            "s3.secret-access-key": AWS_SECRET,
            "s3.path-style-access": "true",
            # Tell PyArrow's S3FileSystem to use the MinIO endpoint too
            "py-io-impl": "pyiceberg.io.pyarrow.PyArrowFileIO",
        },
    )

cat = _catalog()

In [3]:
cat.list_tables(ICEBERG_NS)

[('mch', 'point-forecast_jp2000d0'),
 ('mch', 'point-forecast_jp2000d0_cleaned'),
 ('mch', 'point-forecast_meta_point'),
 ('mch', 'point-forecast_meta_point_cleaned'),
 ('mch', 'point-forecast_point_denormalised')]

In [4]:
TABLE = f"{ICEBERG_NS}.point-forecast_jp2000d0"
table = cat.load_table(TABLE)


# PyIceberg → PyArrow → pandas
df = table.scan().to_pandas()
print(f"Table schema:\n{df.dtypes}\nRow count: {len(df)}")
display(df.head(20))

Table schema:
point_id                       int64
point_type_id                  int64
Date                             str
jp2000d0                       int64
_ingested_at     datetime64[us, UTC]
_source_file                     str
dtype: object
Row count: 50625

,point_id,point_type_id,Date,jp2000d0,_ingested_at,_source_file
0,1,1,202605060000,33,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
1,1,1,202605070000,3,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
2,1,1,202605080000,3,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
3,1,1,202605090000,3,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
4,1,1,202605100000,3,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
5,1,1,202605110000,9,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
6,1,1,202605120000,9,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
7,1,1,202605130000,9,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
8,1,1,202605140000,10,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
9,10,1,202605060000,20,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
10,10,1,202605070000,2,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
11,10,1,202605080000,2,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
12,10,1,202605090000,2,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
13,10,1,202605100000,6,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
14,10,1,202605110000,14,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
15,10,1,202605120000,14,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
16,10,1,202605130000,6,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
17,10,1,202605140000,14,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
18,10101,1,202605060000,20,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...
19,10101,1,202605070000,3,2026-07-23 12:51:11.848956+00:00,s3://raw-data/mch/point-forecast/20260506/vnut...

In [5]:
TABLE = f"{ICEBERG_NS}.point-forecast_jp2000d0_cleaned"
table = cat.load_table(TABLE)

# PyIceberg → PyArrow → pandas
df = table.scan().to_pandas()
print(f"Table schema:\n{df.dtypes}\nRow count: {len(df)}")
display(df.head(20))

Table schema:
point_id                  int64
point_type_id             int64
jp2000d0                  int64
date             datetime64[us]
dtype: object
Row count: 50625

    point_id  point_type_id  jp2000d0       date
0          1              1        33 2026-05-06
1          1              1         3 2026-05-07
2          1              1         3 2026-05-08
3          1              1         3 2026-05-09
4          1              1         3 2026-05-10
5          1              1         9 2026-05-11
6          1              1         9 2026-05-12
7          1              1         9 2026-05-13
8          1              1        10 2026-05-14
9         10              1        20 2026-05-06
10        10              1         2 2026-05-07
11        10              1         2 2026-05-08
12        10              1         2 2026-05-09
13        10              1         6 2026-05-10
14        10              1        14 2026-05-11
15        10              1        14 2026-05-12
16        10              1         6 2026-05-13
17        10              1        14 2026-05-14
18     10101              1        20 2026-05-06
19     10101              1         3 2026-05-07

In [6]:
TABLE = f"{ICEBERG_NS}.point-forecast_meta_point"
table = cat.load_table(TABLE)

# PyIceberg → PyArrow → pandas
df = table.scan().to_pandas()
display(df.head(20))

,point_id,point_type_id,station_abbr,postal_code,point_name,point_type_de,point_type_fr,point_type_it,point_type_en,point_height_masl,point_coordinates_lv95_east,point_coordinates_lv95_north,point_coordinates_wgs84_lat,point_coordinates_wgs84_lon,_ingested_at,_source_file
0,1,1,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,46.792661,9.679014,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
1,2,1,RAG,NaN,Bad Ragaz,Station,Station,Stazione,Station,497.0,2756911.0,1209351.0,47.016631,9.502594,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
2,3,1,HAI,NaN,Salen-Reutenen,Station,Station,Stazione,Station,719.0,2719100.0,1279047.0,47.651242,9.023911,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
3,4,1,HLL,NaN,Hallau,Station,Station,Stazione,Station,419.0,2677457.0,1283472.0,47.697278,8.470464,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
4,6,1,DEM,NaN,Delémont,Station,Station,Stazione,Station,439.0,2593270.0,1244543.0,47.351706,7.349567,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
5,7,1,EBK,NaN,Ebnat-Kappel,Station,Station,Stazione,Station,623.0,2726348.0,1237176.0,47.273389,9.108494,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
6,8,1,ELM,NaN,Elm,Station,Station,Stazione,Station,958.0,2732266.0,1198424.0,46.923742,9.175347,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
7,9,1,EIN,NaN,Einsiedeln,Station,Station,Stazione,Station,911.0,2699984.0,1221068.0,47.133042,8.756556,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
8,10,1,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,46.630914,8.580553,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
9,11,1,MER,NaN,Meiringen,Station,Station,Stazione,Station,589.0,2655844.0,1175930.0,46.732222,8.169247,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
10,13,1,CHD,NaN,Château-d'Oex,Station,Station,Stazione,Station,1028.0,2577040.0,1147655.0,46.479819,7.139656,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
11,14,1,GRA,NaN,Fribourg / Grangeneuve,Station,Station,Stazione,Station,651.0,2575184.0,1180076.0,46.771400,7.113736,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
12,15,1,CHM,NaN,Chaumont,Station,Station,Stazione,Station,1136.0,2565060.0,1211007.0,47.049169,6.978825,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
13,17,1,LAG,NaN,Langnau i.E.,Station,Station,Stazione,Station,744.0,2628004.0,1198793.0,46.939633,7.806425,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
14,18,1,KOP,NaN,Koppigen,Station,Station,Stazione,Station,485.0,2612663.0,1218665.0,47.118850,7.605503,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
15,19,1,GRC,NaN,Grächen,Station,Station,Stazione,Station,1605.0,2630738.0,1116062.0,46.195314,7.836822,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
16,20,1,BLA,NaN,"Blatten, Lötschental",Station,Station,Stazione,Station,1548.0,2629776.0,1141283.0,46.422231,7.825969,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
17,22,1,GRO,NaN,Grono,Station,Station,Stazione,Station,324.0,2733018.0,1124089.0,46.255075,9.163758,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
18,23,1,BEH,NaN,Passo del Bernina,Station,Station,Stazione,Station,2260.0,2798423.0,1143020.0,46.409158,10.019567,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
19,24,1,SIA,NaN,Segl-Maria,Station,Station,Stazione,Station,1804.0,2778576.0,1144976.0,46.432331,9.762325,2026-06-16 10:59:44.930483+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...

In [7]:
TABLE = f"{ICEBERG_NS}.point-forecast_meta_parameters"
table = cat.load_table(TABLE)

# PyIceberg → PyArrow → pandas
df = table.scan().to_pandas()
display(df.head(20))

,parameter_shortname,parameter_description_de,parameter_description_fr,parameter_description_it,parameter_description_en,parameter_group_de,parameter_group_fr,parameter_group_it,parameter_group_en,parameter_granularity,parameter_decimals,parameter_datatype,parameter_unit,_ingested_at,_source_file
0,dkl010h0,Windrichtung; Stundenmittel,Direction du vent; moyenne horaire,Direzione del vento; media oraria,Wind direction; hourly mean,Wind,Vent,Vento,Wind,H,0,Integer,°,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
1,fu3010h0,Windgeschwindigkeit skalar; Stundenmittel in km/h,Vitesse du vent scalaire; moyenne horaire en km/h,Velocità del vento scalare; media oraria in km/h,Wind speed scalar; hourly mean in km/h,Wind,Vent,Vento,Wind,H,1,Float,km/h,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
2,fu3010h1,Böenspitze (Sekundenböe); Stundenmaximum in km/h,Rafale (intégration 1 s); maximum horaire en km/h,Raffica del vento (su un secondo); massima ora...,Gust peak (one second); hourly maximum in km/h,Wind,Vent,Vento,Wind,H,1,Float,km/h,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
3,fu3q10h0,"Windgeschwindigkeit; Stundenmittel, 10% Quanti...","Vitesse du vent; moyenne horaire, quantil 10% ...","Velocità del vento; media oraria, quantile 10%...","Wind speed; hourly mean, 10% quantile in km/h",Wind,Vent,Vento,Wind,H,1,Float,km/h,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
4,fu3q10h1,"Böenspitze; Stundenmaximum, 10% Quantil in km/h","Rafale; maximum horaire, quantil 10% en km/h","Raffica del vento; massima oraria, quantile 10...","Gust peak; hourly maximum, 10% quantile in km/h",Wind,Vent,Vento,Wind,H,1,Float,km/h,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
5,fu3q90h0,"Windgeschwindigkeit; Stundenmittel, 90% Quanti...","Vitesse du vent; moyenne horaire, quantil 90% ...","Velocità del vento; media oraria, quantile 90%...","Wind speed; hourly mean, 90% quantile in km/h",Wind,Vent,Vento,Wind,H,1,Float,km/h,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
6,fu3q90h1,"Böenspitze; Stundenmaximum, 90% Quantil in km/h","Rafale; maximum horaire, quantil 90% en km/h","Raffica del vento; massima oraria, quantile 90...","Gust peak; hourly maximum, 90% quantile in km/h",Wind,Vent,Vento,Wind,H,1,Float,km/h,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
7,gre000h0,Globalstrahlung; Stundenmittel,Rayonnement global; moyenne horaire,Radiazione globale; media oraria,Global radiation; hourly mean,Strahlung,Rayonnement,Radiazione,Radiation,H,0,Integer,W/m²,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
8,jp2000d0,MeteoSchweiz-Piktogramm-Nummer; Tageswert (gül...,"Numéro du pictogramme MétéoSuisse, valeur jour...","Numero del pittogramma di MeteoSvizzera, valor...","MeteoSwiss pictogram number, daily value (vali...",Grafik,Graphique,Grafica,Graphics,D,0,Integer,Code,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
9,jww003i0,MeteoSchweiz-Piktogramm-Nummer; über 3 Stunden,"Numéro du pictogramme MétéoSuisse, valeur sur ...","Numero del pittogramma di MeteoSvizzera, valor...","MeteoSwiss-Icon, weathertype, preceding 3 hour...",Grafik,Graphique,Grafica,Graphics,H,0,Integer,Code,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
10,nprohihs,Hohe Bewölkung,Nébulosité haute,Nuvolosità alte,High cloud cover,Wolken,Nuages,Nubi,Clouds,H,2,Float,-,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
11,nprolohs,Tiefe Bewölkung,Nébulosité basse,Nuvolosità basse,Low cloud cover,Wolken,Nuages,Nubi,Clouds,H,2,Float,-,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
12,npromths,Mittlere Bewölkung,Nébulosité moyenne,Nuvolosità medie,Medium cloud cover,Wolken,Nuages,Nubi,Clouds,H,2,Float,-,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
13,ods000h0,Diffusstrahlung; Stundenmittel,Rayonnement diffus; moyenne horaire,Radiazione diffusa; media oraria,Diffuse radiation; hourly mean,Strahlung,Rayonnement,Radiazione,Radiation,H,0,Integer,W/m²,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
14,rka150d0,Niederschlag; Tagessumme 0 UTC - 0 UTC,Précipitations; somme du jour 0 UTC - 0 UTC,Precipitazioni; somma giornaliera 0 UTC - 0 UTC,Precipitation; daily total 0 UTC - 0 UTC,Niederschlag,Précipitations,Precipitazioni,Precipitation,D,1,Float,mm,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
15,rka150p0,Niederschlag; Tagessumme 00:00 - 24:00 Lokalzeit,Précipitations; somme du jour 00:00 - 24:00 he...,Precipitazioni; somma giornaliera 00:00 - 24:0...,Precipitation; daily total 00:00 - 24:00 local...,Niederschlag,Précipitations,Precipitazioni,Precipitation,D,1,Float,mm,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
16,rp0003i0,Niederschlagswahrscheinlichkeit über 3 Stunden,Probabilité de précipitation sur 3 heures,Probabilità di precipitazioni su 3 ore,Probability of precipitation during 3 hours,Niederschlag,Précipitations,Precipitazioni,Precipitation,H,0,Integer,%,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
17,rre003i0,Niederschlagssumme über 3 Stunden,Précipitations; sommation sur 3 heures,Precipitazioni; somma su 3 ore,Total precipitation during 3 hours,Niederschlag,Précipitations,Precipitazioni,Precipitation,H,1,Float,mm,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
18,rre150h0,Niederschlag; Stundensumme,Précipitations; somme horaire,Precipitazioni; somma oraria,Precipitation; hourly total,Niederschlag,Précipitations,Precipitazioni,Precipitation,H,1,Float,mm,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...
19,rreq10h0,"Niederschlag; Stundensumme, 10% Quantil","Précipitations, somme horaire, quantil 10%","Precipitazioni; somma oraria, quantile 10%","Precipitation; hourly total, 10% quantile",Niederschlag,Précipitations,Precipitazioni,Precipitation,H,1,Float,mm,2026-05-11 11:53:50.027953+00:00,s3://raw-data/mch/point-forecast/ogd-local-for...

In [7]:
# 1. Load the Table
TABLE = f"{ICEBERG_NS}.point-forecast_meta_point_cleaned"
table = cat.load_table(TABLE)

# PyIceberg → PyArrow → pandas
df = table.scan().to_pandas()

# 3. Convert to GeoPandas
# Assuming the geometry column is named 'geom' and is in WKB format
df['geometry'] = df['geometry'].apply(lambda x: shapely.wkb.loads(x))
gdf = gpd.GeoDataFrame(df, geometry='geometry')

# Set CRS if necessary
gdf.crs = "EPSG:2056"


display(gdf.head(20))

,point_id,point_type_id,station_abbr,postal_code,point_name,point_type_de,point_type_fr,point_type_it,point_type_en,point_height_masl,point_coordinates_lv95_east,point_coordinates_lv95_north,geometry
0,1,1,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
1,2,1,RAG,NaN,Bad Ragaz,Station,Station,Stazione,Station,497.0,2756911.0,1209351.0,POINT (2756911 1209351)
2,3,1,HAI,NaN,Salen-Reutenen,Station,Station,Stazione,Station,719.0,2719100.0,1279047.0,POINT (2719100 1279047)
3,4,1,HLL,NaN,Hallau,Station,Station,Stazione,Station,419.0,2677457.0,1283472.0,POINT (2677457 1283472)
4,6,1,DEM,NaN,Delémont,Station,Station,Stazione,Station,439.0,2593270.0,1244543.0,POINT (2593270 1244543)
5,7,1,EBK,NaN,Ebnat-Kappel,Station,Station,Stazione,Station,623.0,2726348.0,1237176.0,POINT (2726348 1237176)
6,8,1,ELM,NaN,Elm,Station,Station,Stazione,Station,958.0,2732266.0,1198424.0,POINT (2732266 1198424)
7,9,1,EIN,NaN,Einsiedeln,Station,Station,Stazione,Station,911.0,2699984.0,1221068.0,POINT (2699984 1221068)
8,10,1,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
9,11,1,MER,NaN,Meiringen,Station,Station,Stazione,Station,589.0,2655844.0,1175930.0,POINT (2655844 1175930)
10,13,1,CHD,NaN,Château-d'Oex,Station,Station,Stazione,Station,1028.0,2577040.0,1147655.0,POINT (2577040 1147655)
11,14,1,GRA,NaN,Fribourg / Grangeneuve,Station,Station,Stazione,Station,651.0,2575184.0,1180076.0,POINT (2575184 1180076)
12,15,1,CHM,NaN,Chaumont,Station,Station,Stazione,Station,1136.0,2565060.0,1211007.0,POINT (2565060 1211007)
13,17,1,LAG,NaN,Langnau i.E.,Station,Station,Stazione,Station,744.0,2628004.0,1198793.0,POINT (2628004 1198793)
14,18,1,KOP,NaN,Koppigen,Station,Station,Stazione,Station,485.0,2612663.0,1218665.0,POINT (2612663 1218665)
15,19,1,GRC,NaN,Grächen,Station,Station,Stazione,Station,1605.0,2630738.0,1116062.0,POINT (2630738 1116062)
16,20,1,BLA,NaN,"Blatten, Lötschental",Station,Station,Stazione,Station,1548.0,2629776.0,1141283.0,POINT (2629776 1141283)
17,22,1,GRO,NaN,Grono,Station,Station,Stazione,Station,324.0,2733018.0,1124089.0,POINT (2733018 1124089)
18,23,1,BEH,NaN,Passo del Bernina,Station,Station,Stazione,Station,2260.0,2798423.0,1143020.0,POINT (2798423 1143020)
19,24,1,SIA,NaN,Segl-Maria,Station,Station,Stazione,Station,1804.0,2778576.0,1144976.0,POINT (2778576 1144976)

In [25]:
TABLE = f"{ICEBERG_NS}.point-forecast_point_denormalised"
table = cat.load_table(TABLE)

# PyIceberg → PyArrow → pandas
df = table.scan().to_pandas()


# 3. Convert to GeoPandas
# Assuming the geometry column is named 'geom' and is in WKB format
df['geometry'] = df['geometry'].apply(lambda x: shapely.wkb.loads(x))
gdf = gpd.GeoDataFrame(df, geometry='geometry')

# Set CRS if necessary
gdf.crs = "EPSG:2056"


display(gdf.head(20))

print(f"Table schema:\n{gdf.dtypes}\nRow count: {len(df)}")
display(df.head(20))

,point_id,point_type_id,jp2000d0,date,station_abbr,postal_code,point_name,point_type_de,point_type_fr,point_type_it,point_type_en,point_height_masl,point_coordinates_lv95_east,point_coordinates_lv95_north,geometry
0,1,1,33,2026-05-06,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
1,1,1,3,2026-05-07,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
2,1,1,3,2026-05-08,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
3,1,1,3,2026-05-09,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
4,1,1,3,2026-05-10,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
5,1,1,9,2026-05-11,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
6,1,1,9,2026-05-12,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
7,1,1,9,2026-05-13,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
8,1,1,10,2026-05-14,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
9,10,1,20,2026-05-06,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
10,10,1,2,2026-05-07,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
11,10,1,2,2026-05-08,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
12,10,1,2,2026-05-09,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
13,10,1,6,2026-05-10,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
14,10,1,14,2026-05-11,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
15,10,1,14,2026-05-12,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
16,10,1,6,2026-05-13,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
17,10,1,14,2026-05-14,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
18,10101,1,20,2026-05-06,ZHEGG,NaN,"Egg, Sihlsee",Station,Station,Stazione,Station,890.0,2701851.0,1223450.0,POINT (2701851 1223450)
19,10101,1,3,2026-05-07,ZHEGG,NaN,"Egg, Sihlsee",Station,Station,Stazione,Station,890.0,2701851.0,1223450.0,POINT (2701851 1223450)

Table schema:
point_id                                 int64
point_type_id                            int64
jp2000d0                                 int64
date                            datetime64[us]
station_abbr                               str
postal_code                            float64
point_name                                 str
point_type_de                              str
point_type_fr                              str
point_type_it                              str
point_type_en                              str
point_height_masl                      float64
point_coordinates_lv95_east            float64
point_coordinates_lv95_north           float64
geometry                              geometry
dtype: object
Row count: 50661

,point_id,point_type_id,jp2000d0,date,station_abbr,postal_code,point_name,point_type_de,point_type_fr,point_type_it,point_type_en,point_height_masl,point_coordinates_lv95_east,point_coordinates_lv95_north,geometry
0,1,1,33,2026-05-06,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
1,1,1,3,2026-05-07,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
2,1,1,3,2026-05-08,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
3,1,1,3,2026-05-09,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
4,1,1,3,2026-05-10,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
5,1,1,9,2026-05-11,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
6,1,1,9,2026-05-12,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
7,1,1,9,2026-05-13,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
8,1,1,10,2026-05-14,ARO,NaN,Arosa,Station,Station,Stazione,Station,1878.0,2771031.0,1184830.0,POINT (2771031 1184830)
9,10,1,20,2026-05-06,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
10,10,1,2,2026-05-07,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
11,10,1,2,2026-05-08,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
12,10,1,2,2026-05-09,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
13,10,1,6,2026-05-10,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
14,10,1,14,2026-05-11,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
15,10,1,14,2026-05-12,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
16,10,1,6,2026-05-13,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
17,10,1,14,2026-05-14,ANT,NaN,Andermatt,Station,Station,Stazione,Station,1435.0,2687445.0,1165044.0,POINT (2687445 1165044)
18,10101,1,20,2026-05-06,ZHEGG,NaN,"Egg, Sihlsee",Station,Station,Stazione,Station,890.0,2701851.0,1223450.0,POINT (2701851 1223450)
19,10101,1,3,2026-05-07,ZHEGG,NaN,"Egg, Sihlsee",Station,Station,Stazione,Station,890.0,2701851.0,1223450.0,POINT (2701851 1223450)